@startuml
'https://plantuml.com/sequence-diagram


left to right direction
actor "cliente" as fc
rectangle  {
  usecase "mostrar menu" as UC1
  usecase "pedir comida" as UC2
}
fc --> UC1
fc --> UC2

left to right direction
actor "restaurante" as rs
rectangle  {
  usecase "mostrar menu" as UC1
}
rs -- (entregar comida)
rs --> UC1

@enduml