@startuml
'https://plantuml.com/sequence-diagram

actor cliente

cliente --> (meter dinero)
cliente --> (pedir azucar)
cliente --> (pedir producto)
cliente --> (cancelar)
(pedir producto) .> (devolver dinero) : include
(cancelar) .> (devolver dinero) : include
@enduml
