@startuml
'https://plantuml.com/sequence-diagram

(+solicitud hecha )<<sacar dinero>>
(" ")<<retener tarjeta>>

note as N1
condición:
{historia sospechosa} punto de extensión:
solicitud hecha
end note

@enduml
<.>